copyright = "© Mark Wylie"
defaultContentLanguage = "en"
enableRobotsTXT = true
languageCode = "en"
timeZone = "America/New_York"
timeout = "120s"
title = "JP Dogs"

[params]
  defaultTheme = "dark"
  description = "This is the website of Mark Wylie, and JP Dogs. Featuring my personal work, and photos I have taken around Jamaica Plain."
  title = "Mark Wylie / JP Dogs"
  [params.author]
    email = "redwylie@gmail.com"
    name = "Mark Wylie"
  [params.socialIcons]
    instagram = "https://www.instagram.com/jamaicaplaindogs"
    email = "mailto:jamaicaplaindogs@gmail.com"
    flickr = "https://flickr.com/photos/redwylie/"

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]

[imaging]
  quality = 95
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription|Orientation"

[module]
  [module.hugoVersion]
    min = "0.121.2"
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery/v4"

[services]
  [services.rss]
    limit = 100

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"